### ISSUE TITLE
program exits with error 'The node #### is not in the graph'

### ISSUE THREAD

**Issue by avialee** [aakechin/NGS-PrimerPlex#21]
I am running NGS-PrimerPlex for a panel with ~2000 snps. 

It did give some warnings that for some regions no primers left after filtering primers by specificity and that cover SNPs! There is an unreachable region '#### is not reachable from #####'. 

The program failed and exits with the error shown below:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1082, in neighbors_iter
    return iter(self.adj[n])
KeyError: 48954199

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "NGS_primerplex.py", line 1892, in joinAmpliconsToBlocks
    path=tuple(nx.algorithms.shortest_paths.generic.shortest_path(blockGraph,firstNodes[i],lastNodes[i]))
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 136, in shortest_path
    paths=nx.bidirectional_shortest_path(G,source,target)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 136, in bidirectional_shortest_path
    results=_bidirectional_pred_succ(G,source,target)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 186, in _bidirectional_pred_succ
    for w in Gsucc(v):
  File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1084, in neighbors_iter
    raise NetworkXError("The node %s is not in the graph." % (n,))
networkx.exception.NetworkXError: The node 48954199 is not in the graph.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "NGS_primerplex.py", line 3380, in <module>
    poolArgs):#results:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
networkx.exception.NetworkXError: The node 48954199 is not in the graph.

I guess it happened during 'Joining primer pairs to amplified blocks...'.  Should I remove the unreachable or uncovered regions and run it again?

**Comment by aakechin** [comment]
@avialee Thank you for this comment! This bug is being fixed now. Sorry for this inconvenience!

**Comment by aakechin** [comment]
Try the new version of the NGS-PrimerPlex: https://github.com/aakechin/NGS-PrimerPlex/releases/tag/v1.3.0

**Comment by Vickymj93** [comment]
Joining primer pairs to amplified blocks...
0.0%multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1082, in neighbors_iter
    return iter(self.adj[n])
KeyError: 55019216

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "NGS_primerplex.py", line 1892, in joinAmpliconsToBlocks
    path=tuple(nx.algorithms.shortest_paths.generic.shortest_path(blockGraph,firstNodes[i],lastNodes[i]))
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 136, in shortest_path
    paths=nx.bidirectional_shortest_path(G,source,target)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 136, in bidirectional_shortest_path
    results=_bidirectional_pred_succ(G,source,target)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 186, in _bidirectional_pred_succ
    for w in Gsucc(v):
  File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1084, in neighbors_iter
    raise NetworkXError("The node %s is not in the graph." % (n,))
networkx.exception.NetworkXError: The node 55019216 is not in the graph.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "NGS_primerplex.py", line 3378, in <module>
    poolArgs):#results:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
networkx.exception.NetworkXError: The node 55019216 is not in the graph.

I have been facing a similar error when trying to run for a handful of SNVs (10-15). Trying to design short ampicons of size ~150bp. Any help would be appreciated.
