### ISSUE TITLE
Analyzing primers for their specificity... IndexError: string index out of range

### ISSUE THREAD

**Issue by ARVINDEN** [aakechin/NGS-PrimerPlex#29]
Hi,
I am trying to read from draft file and trying to make multiplex primer with -blast option but failed in checking for checking non specific region step, I have pasted error message below, please help me resolve this error.

Reading input file...
Total number of input point regions: 5627
Number of unique input point regions: 5627
Reading file with draft primers and checking them for interactions...
Number of primer pairs from draft file: 65535
That do not form secondary structures: 65535
Getting positions that uncovered by draft primers...
Total number of uncovered positions: 0
Analyzing primers for their specificity...
 Running BWA...
 Processing SAM-file...
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
  File "/NGS-PrimerPlex/NGS_primerplex.py", line 3291, in <module>
    args.maxNonSpecLen,args.maxPrimerNonspec,False,'',args.blastNum)    
  File "/NGS-PrimerPlex/NGS_primerplex.py", line 1310, in checkPrimersSpecificity
    res=res.get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/NGS-PrimerPlex/NGS_primerplex.py", line 1543, in readBwaFile
    regionSeq[-2]==primerSeq[-2]):
IndexError: string index out of range

**Comment by aakechin** [comment]
@ARVINDEN Thank you for the question and sorry for such a delay with an answer. I think the problem may be with the BWA. Possibly it was terminated due to low memory with a "Segmentation fault" error, and this type of error cannot be caught. Could you check your SAM-file with less?

**Comment by realgoldace** [comment]
Dear Dr.aakechin: 
I met the same problem too, and I got '' # Total number of constructed primers: 46355395
 # Total number of different constructed primers: 502178
Analyzing primers for their specificity...
 Running BWA...
 Processing SAM-file...
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
0.05%[E::fai_retrieve] Failed to retrieve block: unexpected end of file
1.76%[E::fai_retrieve] Failed to retrieve block: unexpected end of file
2.43%[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
2.58%[E::fai_retrieve] Failed to retrieve block: unexpected end of file
2.59%[E::fai_retrieve] Failed to retrieve block: unexpected end of file
2.65%[E::fai_retrieve] Failed to retrieve block: unexpected end of file
2.69%Traceback (most recent call last):
  File "NGS_primerplex.py", line 3291, in <module>
    args.maxNonSpecLen,args.maxPrimerNonspec,False,'',args.blastNum)
  File "NGS_primerplex.py", line 1310, in checkPrimersSpecificity
    res=res.get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "NGS_primerplex.py", line 1543, in readBwaFile
    regionSeq[-2]==primerSeq[-2]):
IndexError: string index out of range", I suspected the Integrity of the sam file, however by running "samtools quickcheck .bwa.sam", I got no output.

**Comment by realgoldace** [comment]
When the input bed region was big, and the designed primer number excess 1 million, this error seems to be always occured, could there be any advices? thank you very much!

**Comment by aakechin** [comment]
@realgoldace Thank you for the question. Did you use the last version of the NGS-PrimerPlex? Some bugs were fixed since 2022. And which NGS-PrimerPlex version (gui or command-line, with or without docker) and with which OS did you use the program? And what was the reference genome?

**Comment by realgoldace** [comment]
Dear Dr.Andrey Kechin:

Thank you for your kindly answers,

I used the docker of the latest version which was downloaded at April this year, and the command was 

 

dockerrun-it--entrypoint'bash'--namengs_primerplex_ref--rm-v/data10/luqin/multiplex:/multiplexaakechin/ngs-primerplex:latest




'python3NGS_primerplex.py--regions-file/multiplex/inter_neuron.bed--max-amplicon-length275--optimal-amplicon-length220--optimal-primer-melting-temp60--min-primer-melting-temp58-refhg19/ucsc.hg19.fasta-blast-snps-dbsnphg19/common_all_20180423_hg19.vcf.gz--threads20--skip-uncovered--min-primer-end-gc0--opt-primer-end-gc3'

The reference and snp file was preseted in the docker, and the reference version was hg19, the program was ran on the following OS:Linux version 3.10.0-1160.83.1.el7.x86_64 ***@***.***)(gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Jan 25 16:41:43 UTC 2023 Jan 25 16:41:43 UTC 2023.

And the bed was attached as appendix.

Sincerely yours

Qin Lu

 

-----原始邮件-----
发件人:aakechin ***@***.***>
发送时间:2023-06-05 16:23:26 (星期一)
收件人: aakechin/NGS-PrimerPlex ***@***.***>
抄送: realgoldace ***@***.***>, Mention ***@***.***>
主题: Re: [aakechin/NGS-PrimerPlex] Analyzing primers for their specificity... IndexError: string index out of range (Issue #29)






@realgoldace Thank you for the question. Did you use the last version of the NGS-PrimerPlex? Some bugs were fixed since 2022. And which NGS-PrimerPlex version (gui or command-line, with or without docker) and with which OS did you use the program? And what was the reference genome?
