### ISSUE TITLE
Failed to generate xlsx file

### ISSUE THREAD

**Issue by MagpiePKU** [aakechin/NGS-PrimerPlex#36]
Hi,

Thanks for the great tool. We tested it on a customized genome but got following error:

Traceback (most recent call last):
  File "~/NGS-PrimerPlex//NGS_primerplex.py", line 3283, in <module>
    primersInfo,primersInfoByChrom,amplNames,primersToAmplNames,regionsCoords,regionNameToChrom,allRegions=constructInternalPrimers(primer3Params,regionNameToChrom,args,regionsCoords,allRegions)
  File "~/NGS-PrimerPlex//NGS_primerplex.py", line 574, in constructInternalPrimers
    writeDraftPrimers(primersInfo,args.regionsFile[:-4]+'_all_draft_primers.xls')
  File "~/NGS-PrimerPlex//NGS_primerplex.py", line 910, in writeDraftPrimers
    wb=xlrd.open_workbook(rFile)
  File "~/tools/software/anaconda3/lib/python3.8/site-packages/xlrd/__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported

The XLRD version is 2.0.1 

It seems like it was intended to write .xls file instead of .xlsx but somehow the data format is xlsx?

**Comment by aakechin** [comment]
@MagpiePKU The problem may be in the xlrd or xlsxwriter module. Could you write the xlsxwriter version? My xlrd version is 1.2.5. Could you try to install xlrd version 1.2.5?
