### ISSUE TITLE
ERROR after BWA

### ISSUE THREAD

**Issue by rolibudhwar** [aakechin/NGS-PrimerPlex#46]
@aakechin Could you pls help solving this error

/home/bion480g/Programs/NGS-PrimerPlex-omaster/NGS_primerplex.py -regions results.csv -ref /home/bion480g/Programs/NGS-PrimerPlex-master/BC/REF/hg38.fa --min-primer-melting-temp 58 --max-primer-melting-temp 64 --min-amplicon 180 --max-amplicon-length 200 --primers-number1 100 --draft-primers results_all_draft_primers.xls --do-blast -th 20 --snps --dbsnp /home/bion480g/SQITDB/Exome/hg38/dbSNP.hg38.vcf.gz
Reading input file...
 # Total number of input point regions: 55337
 # Number of unique input point regions: 55337
Reading file with draft primers and checking them for interactions...
100.0%
 # Number of primer pairs from draft file: 1048575
 # That do not form secondary structures: 1048575
Getting positions that uncovered by draft primers...
 # Total number of uncovered positions: 28592
Creating input parameters for primer3...
Constructing primers...
100.0%
 # Total number of constructed primers: 114519928
 # Total number of different constructed primers: 630933
Total number of primer pairs: 1679508
Analyzing primers for their specificity...
 Running BWA...
 Processing SAM-file...
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
2.51%Traceback (most recent call last):
  File "/home/bion480g/Programs/NGS-PrimerPlex-master/NGS_primerplex.py", line 3701, in <module>
    specificPrimers,primersNonSpecRegionsByChrs=checkPrimersSpecificity(args.regionsFile[:-4],primersInfo,primersToAmplNames,
  File "/home/bion480g/Programs/NGS-PrimerPlex-master/NGS_primerplex.py", line 1516, in checkPrimersSpecificity
    res=res.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/bion480g/Programs/NGS-PrimerPlex-master/NGS_primerplex.py", line 1787, in readBwaFile
    regionSeq[-2]==primerSeq[-2]) and

**Comment by aakechin** [comment]
@rolibudhwar As I could see in the log-file, the error was before the BWA. The program says that with the defined parameters, for many target regions, primers could not be designed. First of all, I would suggest you to run the program with low value for the -primernum1 parameter and other parameters by default. Then, for part of the target regions, primers will be designed and written into the draft file. Then, using this draft file and making parameters less stringent, try to design primers. Repeat this step again and again, making parameters less stringent each cycle.
