### ISSUE TITLE
I think there is a big problem when design about 150 multiplex primer. Please check the run below.

### ISSUE THREAD

**Issue by HFyange** [aakechin/NGS-PrimerPlex#56]
@aakechin  Hi:
I couldnot get design result using regions and command below by the 1.3.4 version. Always run error detecting specifity. 
# 1. The regions:
chr1 | 115252189 | 115252349 | 1 | 1 | B | NotW
chr1 | 115256459 | 115256562 | 2 | 1 | B | NotW
chr1 | 115258670 | 115258798 | 3 | 1 | B | NotW
chr1 | 156846341 | 156846343 | 4 | 1 | B | NotW
chr1 | 156849106 | 156849108 | 5 | 1 | B | NotW
chr2 | 29419649 | 29419651 | 6 | 1 | B | NotW
chr2 | 29432654 | 29432656 | 7 | 1 | B | NotW
chr2 | 29432663 | 29432665 | 8 | 1 | B | NotW
chr2 | 29432681 | 29432683 | 9 | 1 | B | NotW
chr2 | 29436858 | 29436861 | 10 | 1 | B | NotW
chr2 | 29443588 | 29443590 | 11 | 1 | B | NotW
chr2 | 29443599 | 29443601 | 12 | 1 | B | NotW
chr2 | 29443609 | 29443611 | 13 | 1 | B | NotW
chr2 | 29443612 | 29443614 | 14 | 1 | B | NotW
chr2 | 29443624 | 29443626 | 15 | 1 | B | NotW
chr2 | 29443630 | 29443632 | 16 | 1 | B | NotW
chr2 | 29443641 | 29443644 | 17 | 1 | B | NotW
chr2 | 29443678 | 29443680 | 18 | 1 | B | NotW
chr2 | 29443694 | 29443696 | 19 | 1 | B | NotW
chr2 | 29445212 | 29445214 | 20 | 1 | B | NotW
chr2 | 29445215 | 29445217 | 21 | 1 | B | NotW
chr2 | 29445227 | 29445229 | 22 | 1 | B | NotW
chr2 | 29445257 | 29445259 | 23 | 1 | B | NotW
chr2 | 29445269 | 29445271 | 24 | 1 | B | NotW
chr2 | 29445449 | 29445451 | 25 | 1 | B | NotW
chr2 | 29446381 | 29446383 | 26 | 1 | B | NotW
chr2 | 29451922 | 29451924 | 27 | 1 | B | NotW
chr2 | 29474093 | 29474095 | 28 | 1 | B | NotW
chr2 | 29519780 | 29519782 | 29 | 1 | B | NotW
chr3 | 178916685 | 178916772 | 30 | 1 | B | NotW
chr3 | 178916844 | 178916846 | 31 | 1 | B | NotW
chr3 | 178916851 | 178916949 | 32 | 1 | B | NotW
chr3 | 178917425 | 178917497 | 33 | 1 | B | NotW
chr3 | 178919166 | 178919168 | 34 | 1 | B | NotW
chr3 | 178921547 | 178921574 | 35 | 1 | B | NotW
chr3 | 178922297 | 178922376 | 36 | 1 | B | NotW
chr3 | 178927907 | 178927988 | 37 | 1 | B | NotW
chr3 | 178928053 | 178928116 | 38 | 1 | B | NotW
chr3 | 178928225 | 178928227 | 39 | 1 | B | NotW
chr3 | 178928273 | 178928275 | 40 | 1 | B | NotW
chr3 | 178937053 | 178937055 | 41 | 1 | B | NotW
chr3 | 178947809 | 178947899 | 42 | 1 | B | NotW
chr3 | 178948043 | 178948045 | 43 | 1 | B | NotW
chr3 | 178948135 | 178948137 | 44 | 1 | B | NotW
chr3 | 178951992 | 178952096 | 45 | 1 | B | NotW
chr4 | 1803563 | 1803565 | 46 | 1 | B | NotW
chr4 | 1803567 | 1803569 | 47 | 1 | B | NotW
chr4 | 1806088 | 1806090 | 48 | 1 | B | NotW
chr4 | 1806098 | 1806100 | 49 | 1 | B | NotW
chr6 | 117630061 | 117630063 | 50 | 1 | B | NotW
chr6 | 117631421 | 117631423 | 51 | 1 | B | NotW
chr6 | 117638343 | 117638345 | 52 | 1 | B | NotW
chr6 | 117638346 | 117638348 | 53 | 1 | B | NotW
chr6 | 117638364 | 117638366 | 54 | 1 | B | NotW
chr6 | 117639357 | 117639359 | 55 | 1 | B | NotW
chr6 | 117639398 | 117639400 | 56 | 1 | B | NotW
chr6 | 117641118 | 117641120 | 57 | 1 | B | NotW
chr7 | 55210074 | 55210076 | 58 | 1 | B | NotW
chr7 | 55211079 | 55211081 | 59 | 1 | B | NotW
chr7 | 55221742 | 55221744 | 60 | 1 | B | NotW
chr7 | 55221821 | 55221823 | 61 | 1 | B | NotW
chr7 | 55238897 | 55238975 | 62 | 1 | B | NotW
chr7 | 55241613 | 55241736 | 63 | 1 | B | NotW
chr7 | 55242415 | 55242513 | 64 | 1 | B | NotW
chr7 | 55248985 | 55249171 | 65 | 1 | B | NotW
chr7 | 55259412 | 55259567 | 66 | 1 | B | NotW
chr7 | 55260482 | 55260484 | 67 | 1 | B | NotW
chr7 | 116339601 | 116339692 | 68 | 1 | B | NotW
chr7 | 116411867 | 116412110 | 69 | 1 | B | NotW
chr7 | 116423393 | 116423486 | 70 | 1 | B | NotW
chr7 | 116435979 | 116436059 | 71 | 1 | B | NotW
chr7 | 140453074 | 140453193 | 72 | 1 | B | NotW
chr7 | 140481375 | 140481493 | 73 | 1 | B | NotW
chr8 | 38272266 | 38272359 | 74 | 1 | B | NotW
chr8 | 38273445 | 38273489 | 75 | 1 | B | NotW
chr8 | 38273560 | 38273562 | 76 | 1 | B | NotW
chr8 | 38274848 | 38274850 | 77 | 1 | B | NotW
chr8 | 38275808 | 38275829 | 78 | 1 | B | NotW
chr8 | 38282155 | 38282252 | 79 | 1 | B | NotW
chr10 | 43606903 | 43606910 | 80 | 1 | B | NotW
chr10 | 43607600 | 43607622 | 81 | 1 | B | NotW
chr10 | 43609023 | 43609123 | 82 | 1 | B | NotW
chr10 | 43609927 | 43609995 | 83 | 1 | B | NotW
chr10 | 43610044 | 43610140 | 84 | 1 | B | NotW
chr10 | 43613820 | 43613928 | 85 | 1 | B | NotW
chr10 | 43614995 | 43614997 | 86 | 1 | B | NotW
chr10 | 43615002 | 43615004 | 87 | 1 | B | NotW
chr10 | 43615082 | 43615084 | 88 | 1 | B | NotW
chr10 | 43615128 | 43615130 | 89 | 1 | B | NotW
chr10 | 43615141 | 43615143 | 90 | 1 | B | NotW
chr10 | 43615528 | 43615611 | 91 | 1 | B | NotW
chr10 | 43617393 | 43617464 | 92 | 1 | B | NotW
chr10 | 89624226 | 89624305 | 93 | 1 | B | NotW
chr10 | 89653781 | 89653866 | 94 | 1 | B | NotW
chr10 | 89685269 | 89685314 | 95 | 1 | B | NotW
chr10 | 89690802 | 89690846 | 96 | 1 | B | NotW
chr10 | 89692769 | 89692830 | 97 | 1 | B | NotW
chr10 | 89717632 | 89717701 | 98 | 1 | B | NotW
chr10 | 89717737 | 89717805 | 99 | 1 | B | NotW
chr10 | 89725042 | 89725064 | 100 | 1 | B | NotW
chr10 | 123247568 | 123247570 | 101 | 1 | B | NotW
chr10 | 123258033 | 123258035 | 102 | 1 | B | NotW
chr10 | 123274793 | 123274795 | 103 | 1 | B | NotW
chr10 | 123279673 | 123279675 | 104 | 1 | B | NotW
chr10 | 123279676 | 123279678 | 105 | 1 | B | NotW
chr10 | 123310909 | 123310931 | 106 | 1 | B | NotW
chr12 | 25362829 | 25362831 | 107 | 1 | B | NotW
chr12 | 25362837 | 25362839 | 108 | 1 | B | NotW
chr12 | 25378528 | 25378681 | 109 | 1 | B | NotW
chr12 | 25380167 | 25380346 | 110 | 1 | B | NotW
chr12 | 25398211 | 25398306 | 111 | 1 | B | NotW
chr14 | 105239278 | 105239280 | 112 | 1 | B | NotW
chr14 | 105239403 | 105239405 | 113 | 1 | B | NotW
chr14 | 105239412 | 105239414 | 114 | 1 | B | NotW
chr14 | 105239419 | 105239421 | 115 | 1 | B | NotW
chr14 | 105239424 | 105239426 | 116 | 1 | B | NotW
chr14 | 105239807 | 105239809 | 117 | 1 | B | NotW
chr14 | 105239810 | 105239812 | 118 | 1 | B | NotW
chr14 | 105239819 | 105239821 | 119 | 1 | B | NotW
chr14 | 105241323 | 105241325 | 120 | 1 | B | NotW
chr14 | 105241335 | 105241337 | 121 | 1 | B | NotW
chr14 | 105241412 | 105241414 | 122 | 1 | B | NotW
chr14 | 105243043 | 105243045 | 123 | 1 | B | NotW
chr14 | 105243047 | 105243051 | 124 | 1 | B | NotW
chr14 | 105243052 | 105243054 | 125 | 1 | B | NotW
chr14 | 105246435 | 105246437 | 126 | 1 | B | NotW
chr14 | 105246441 | 105246443 | 127 | 1 | B | NotW
chr14 | 105246444 | 105246446 | 128 | 1 | B | NotW
chr14 | 105246454 | 105246456 | 129 | 1 | B | NotW
chr14 | 105246481 | 105246483 | 130 | 1 | B | NotW
chr14 | 105246531 | 105246533 | 131 | 1 | B | NotW
chr14 | 105246550 | 105246552 | 132 | 1 | B | NotW
chr15 | 66727375 | 66727484 | 133 | 1 | B | NotW
chr15 | 66729083 | 66729175 | 134 | 1 | B | NotW
chr15 | 66735617 | 66735695 | 135 | 1 | B | NotW
chr15 | 66736993 | 66737045 | 136 | 1 | B | NotW
chr15 | 66774097 | 66774198 | 137 | 1 | B | NotW
chr15 | 88472467 | 88472469 | 138 | 1 | B | NotW
chr15 | 88476264 | 88476266 | 139 | 1 | B | NotW
chr15 | 88476282 | 88476284 | 140 | 1 | B | NotW
chr17 | 7573926 | 7574033 | 141 | 1 | B | NotW
chr17 | 7576852 | 7576926 | 142 | 1 | B | NotW
chr17 | 7577018 | 7577041 | 143 | 1 | B | NotW
chr17 | 7577062 | 7577155 | 144 | 1 | B | NotW
chr17 | 7577506 | 7577598 | 145 | 1 | B | NotW
chr17 | 7578181 | 7578286 | 146 | 1 | B | NotW
chr17 | 7578370 | 7578480 | 147 | 1 | B | NotW
chr17 | 7578516 | 7578554 | 148 | 1 | B | NotW
chr17 | 7579317 | 7579415 | 149 | 1 | B | NotW
chr17 | 37866343 | 37866345 | 150 | 1 | B | NotW
chr17 | 37866358 | 37866360 | 151 | 1 | B | NotW
chr17 | 37866625 | 37866627 | 152 | 1 | B | NotW
chr17 | 37866661 | 37866663 | 153 | 1 | B | NotW
chr17 | 37866706 | 37866708 | 154 | 1 | B | NotW
chr17 | 37868175 | 37868268 | 155 | 1 | B | NotW
chr17 | 37868278 | 37868280 | 156 | 1 | B | NotW
chr17 | 37871996 | 37871998 | 157 | 1 | B | NotW
chr17 | 37872137 | 37872139 | 158 | 1 | B | NotW
chr17 | 37873723 | 37873725 | 159 | 1 | B | NotW
chr17 | 37876070 | 37876077 | 160 | 1 | B | NotW
chr17 | 37876086 | 37876088 | 161 | 1 | B | NotW
chr17 | 37879554 | 37879660 | 162 | 1 | B | NotW
chr17 | 37879668 | 37879671 | 163 | 1 | B | NotW
chr17 | 37879672 | 37879674 | 164 | 1 | B | NotW
chr17 | 37879680 | 37879682 | 165 | 1 | B | NotW
chr17 | 37879701 | 37879703 | 166 | 1 | B | NotW
chr17 | 37879830 | 37879832 | 167 | 1 | B | NotW
chr17 | 37879833 | 37879835 | 168 | 1 | B | NotW
chr17 | 37879853 | 37879855 | 169 | 1 | B | NotW
chr17 | 37879859 | 37879862 | 170 | 1 | B | NotW
chr17 | 37879880 | 37879882 | 171 | 1 | B | NotW
chr17 | 37879902 | 37879904 | 172 | 1 | B | NotW
chr17 | 37880200 | 37880286 | 173 | 1 | B | NotW
chr17 | 37880978 | 37881164 | 174 | 1 | B | NotW
chr17 | 37881323 | 37881325 | 175 | 1 | B | NotW
chr17 | 37881326 | 37881420 | 176 | 1 | B | NotW
chr17 | 37881439 | 37881441 | 177 | 1 | B | NotW
chr17 | 37881615 | 37881617 | 178 | 1 | B | NotW
chr17 | 37881976 | 37881978 | 179 | 1 | B | NotW
chr17 | 37883102 | 37883104 | 180 | 1 | B | NotW
chr17 | 37884221 | 37884224 | 181 | 1 | B | NotW
# 2. command:
python3 NGS_primerplex.py \
-regions /file path \
-ref hg19/ucsc.hg19.fasta \
-maxprimerendgc 3 \
-maxprimergc 70 \
-minprimergc 20 \
-minampllen 90 \
-optampllen 110 \
-maxampllen 130 \ #the max amp len is 130 bp（to amplify ct DNA）
-minprimermelt 59 \
-optprimermelt 61 \
-maxprimermelt 63 \
-maxprimerlen 30 \
-blast \
-snps \
-nucs 10 \
-th 6 \
-dbsnp hg19/common_all_20180423_hg19.vcf.gz \
-minmultdimerdg1 -5 \
-minmultdimerdg2 -10 \
-primernum1 50 \
-maxoverlap 150 \
# 3. my computer info: windows 10  16GRAM   NGS-primer v1.3.4 docker version

**Comment by HFyange** [comment]
Running BWA...
Processing SAM-file...
100.0%
Total number of nonspecific regions: 1779212
Searching for nonspecific amplicons that are formed by designed primer pairs...
Number of specific primer pairs: 15996
Removing unspecific primer pairs...
Searching for nonspecific amplicons that are formed by primers from different primer pairs...
94.13%Segmentation fault
Process ForkPoolWorker-12:
Traceback (most recent call last):
File "/usr/lib/python3.5/multiprocessing/pool.py", line 125, in worker
put((job, i, result))
File "/usr/lib/python3.5/multiprocessing/queues.py", line 355, in put
self._writer.send_bytes(obj)
File "/usr/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
self._send_bytes(m[offset:offset + size])
File "/usr/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
self._send(header + buf)
File "/usr/lib/python3.5/multiprocessing/connection.py", line 368, in _send
n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
self.run()
File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.5/multiprocessing/pool.py", line 130, in worker
put((job, i, (False, wrapped)))
File "/usr/lib/python3.5/multiprocessing/queues.py", line 355, in put
self._writer.send_bytes(obj)
File "/usr/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
self._send_bytes(m[offset:offset + size])
File "/usr/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
self._send(header + buf)
File "/usr/lib/python3.5/multiprocessing/connection.py", line 368, in _send
n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
