### ISSUE TITLE
The node 55019216 is not in the graph.

### ISSUE THREAD

**Issue by Vickymj93** [aakechin/NGS-PrimerPlex#57]
Joining primer pairs to amplified blocks...
0.0%multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1082, in neighbors_iter
return iter(self.adj[n])
KeyError: 55019216

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "NGS_primerplex.py", line 1892, in joinAmpliconsToBlocks
path=tuple(nx.algorithms.shortest_paths.generic.shortest_path(blockGraph,firstNodes[i],lastNodes[i]))
File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 136, in shortest_path
paths=nx.bidirectional_shortest_path(G,source,target)
File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 136, in bidirectional_shortest_path
results=_bidirectional_pred_succ(G,source,target)
File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 186, in _bidirectional_pred_succ
for w in Gsucc(v):
File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1084, in neighbors_iter
raise NetworkXError("The node %s is not in the graph." % (n,))
networkx.exception.NetworkXError: The node 55019216 is not in the graph.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "NGS_primerplex.py", line 3378, in
poolArgs):#results:
File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
raise value
networkx.exception.NetworkXError: The node 55019216 is not in the graph.

I have been facing a similar error, to the one which user @avialee was facing, when trying to run for a handful of SNVs (10-15). Trying to design short ampicons of size ~150bp. Any help would be appreciated.

**Comment by Vickymj93** [comment]
Although it has been working like a charm for preparing multiplex primers for amplifying regions more than 500 bp, I encountered the error mentioned above recently when running it for specifically a set of 15 defined variants in the regions file for amplification of 150bp products.

**Comment by aakechin** [comment]
@Vickymj93 Did you use the latest version of the NGS-PrimerPlex? 150 bp was not problem for the program. There may be other issues...

**Comment by aakechin** [comment]
As I see in your issue description, line numbers do not correspond to the latest version. Please, try download the latest one, and try it again. Please, give me feedback about the result.

**Comment by Vickymj93** [comment]
Facing the same error with a new line number when I tried to run it with the updated NGS-Primerplex1.3.4

Joining primer pairs to amplified blocks...
0.0%multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1082, in neighbors_iter
    return iter(self.adj[n])
KeyError: 55019216

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "NGS_primerplex.py", line 2192, in joinAmpliconsToBlocks
    path=tuple(nx.algorithms.shortest_paths.generic.shortest_path(blockGraph,firstNodes[i],lastNodes[i]))
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 136, in shortest_path
    paths=nx.bidirectional_shortest_path(G,source,target)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 136, in bidirectional_shortest_path
    results=_bidirectional_pred_succ(G,source,target)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 186, in _bidirectional_pred_succ
    for w in Gsucc(v):
  File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1084, in neighbors_iter
    raise NetworkXError("The node %s is not in the graph." % (n,))
networkx.exception.NetworkXError: The node 55019216 is not in the graph.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "NGS_primerplex.py", line 3795, in <module>
    poolArgs):#results:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
networkx.exception.NetworkXError: The node 55019216 is not in the graph.

**Comment by petersam23** [comment]
Great program. Thank you very much.  I have also recently run into this problem. I don't see why amplicon length would matter but mine was aimed at 160.  It still comes up with a list of draft primers after checking for specificity but seems to have problems when attempting to assemble different pools. Log below if it helps.
------

 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1082, in neighbors_iter
     return iter(self.adj[n])
 KeyError: 20102
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
     result = (True, func(*args, **kwds))
   File "/NGS-PrimerPlex/NGS_primerplex.py", line 2192, in joinAmpliconsToBlocks
     path=tuple(nx.algorithms.shortest_paths.generic.shortest_path(blockGraph,firstNodes[i],lastNodes[i]))
   File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 136, in shortest_path
     paths=nx.bidirectional_shortest_path(G,source,target)
   File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 136, in bidirectional_shortest_path
     results=_bidirectional_pred_succ(G,source,target)
   File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 186, in _bidirectional_pred_succ
     for w in Gsucc(v):
   File "/usr/local/lib/python3.5/dist-packages/networkx/classes/graph.py", line 1084, in neighbors_iter
     raise NetworkXError("The node %s is not in the graph." % (n,))
 networkx.exception.NetworkXError: The node 20102 is not in the graph.
 """
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/NGS-PrimerPlex/NGS_primerplex.py", line 3795, in <module>
     poolArgs):#results:
   File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
     raise value

**Comment by Rea163** [comment]
I am experiencing the same issue as mentioned above when running NGS-PrimerPlex. It generates a list of draft internal primers after checking for specificity, but then an error occurs (see below). I would appreciate it if someone could suggest a solution. Thank you.

_100.0%
Joining primer pairs to amplified blocks...
0.0%

‘’’’’’’’’’’’’’’’
Traceback (most recent call last):
  File "/lustre/nobackup/WUR/ABGC/shared/pipelines_version2/envs/mPCRselect2/lib/python3.7/site-packages/networkx/classes/graph.py", line 1082, in neighbors_iter
    return iter(self.adj[n])
KeyError: 12048376

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/nobackup/WUR/ABGC/shared/pipelines_version2/envs/mPCRselect2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/lustre/nobackup/WUR/ABGC/sharma01/mPCRselect_pipeline/NGS-PrimerPlex/NGS_primerplex.py", line 2192, in joinAmpliconsToBlocks
    path=tuple(nx.algorithms.shortest_paths.generic.shortest_path(blockGraph,firstNodes[i],lastNodes[i]))
  File "/lustre/nobackup/WUR/ABGC/shared/pipelines_version2/envs/mPCRselect2/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 136, in shortest_path
    paths=nx.bidirectional_shortest_path(G,source,target)
  File "/lustre/nobackup/WUR/ABGC/shared/pipelines_version2/envs/mPCRselect2/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 136, in bidirectional_shortest_path
    results=_bidirectional_pred_succ(G,source,target)
  File "/lustre/nobackup/WUR/ABGC/shared/pipelines_version2/envs/mPCRselect2/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 186, in _bidirectional_pred_succ
    for w in Gsucc(v):
  File "/lustre/nobackup/WUR/ABGC/shared/pipelines_version2/envs/mPCRselect2/lib/python3.7/site-packages/networkx/classes/graph.py", line 1084, in neighbors_iter
    raise NetworkXError("The node %s is not in the graph." % (n,))
networkx.exception.NetworkXError: The node 12048376 is not in the graph.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/nobackup/WUR/ABGC/sharma01/mPCRselect_pipeline/NGS-PrimerPlex/NGS_primerplex.py", line 3795, in <module>
    poolArgs):#results:
  File "/lustre/nobackup/WUR/ABGC/shared/pipelines_version2/envs/mPCRselect2/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
networkx.exception.NetworkXError: The node 12048376 is not in the graph._
